apiVersion: v1
kind: Service
metadata:
  name: rider-backend
  namespace: fleet
spec:
  type: ClusterIP
  selector:
    app: rider-backend
  ports:
    - name: http
      port: 4000
      targetPort: 4000
